INSERT INTO products (name, description, quantity, image, price, category)
VALUES ('Artichokes', 'Fresh delicious artichokes', 10, './public/docs/artichoke', 3.99, 'Vegetables');
-- INSERT INTO products (name, description, quantity, image, price, category, store_id)
-- VALUES ('Asparagus', './docs/asparagus', 'Asparagus', 2.99, 'Vegetables');
-- INSERT INTO products (name, description, quantity, image, price, category, store_id)
-- VALUES ('Cabbage', './docs/cabbage', 'individual cabbage', 1.99, 'Vegetables');
-- INSERT INTO products (name, description, quantity, image, price, category, store_id)
-- VALUES ('Eggplant', 'IMAGE', 'eggplant', 1.99, 'Vegetables');
-- INSERT INTO products (name, description, quantity, image, price, category, store_id)
-- VALUES ('Onions', 'IMAGE', 'bags of onions', 3.99, 'Vegetables');
-- INSERT INTO products (name, description, quantity, image, price, category, store_id)
-- VALUES ('Parsnip', 'IMAGE', 'parsnips', 0.99, 'Vegetables');
-- INSERT INTO products (name, description, quantity, image, price, category, store_id)
-- VALUES ('Radishes', 'IMAGE', 'Radishes', 2.99, 'Vegetables');
-- INSERT INTO products (name, description, quantity, image, price, category, store_id)
-- VALUES ('Tomatoes', 'IMAGE', 'Tomatoes', 2.99, 'Vegetables');
-- INSERT INTO products (name, description, quantity, image, price, category, store_id)
-- VALUES ('Avocado', 'IMAGE', 'Avocado', 9.99, 'Vegetables');

-- INSERT INTO products (name, description, quantity, image, price, category, store_id)
-- VALUES ('Blueberries', 'IMAGE', 'Blueberries', 3.99, 'Fruits');
-- INSERT INTO products (name, description, quantity, image, price, category, store_id)
-- VALUES ('Raspberries', 'IMAGE', 'Raspberries', 3.99, 'Fruits');
-- INSERT INTO products (name, description, quantity, image, price, category, store_id)
-- VALUES ('Apples', 'IMAGE', 'Apples', 4.99, 'Fruits');
-- INSERT INTO products (name, description, quantity, image, price, category, store_id)
-- VALUES ('Strawberries', 'IMAGE', 'Strawberries', 3.49, 'Fruits');
-- INSERT INTO products (name, description, quantity, image, price, category, store_id)
-- VALUES ('Pineapple', 'IMAGE', 'Pineapple', 5.99, 'Fruits');
-- INSERT INTO products (name, description, quantity, image, price, category, store_id)
-- VALUES ('Grapefruit', 'IMAGE', 'Grapefruit', 2.99, 'Fruits');